"""Remove unique in vote history

Revision ID: 50e79e826739
Revises: 75dae851eded
Create Date: 2023-05-27 18:25:50.024236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e79e826739'
down_revision = '75dae851eded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes_history', schema=None) as batch_op:
        batch_op.drop_constraint('votes_history_cat_pk_key', type_='unique')
        batch_op.drop_constraint('votes_history_voter_pk_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes_history', schema=None) as batch_op:
        batch_op.create_unique_constraint('votes_history_voter_pk_key', ['voter_pk'])
        batch_op.create_unique_constraint('votes_history_cat_pk_key', ['cat_pk'])

    # ### end Alembic commands ###
