"""Add color and birth date

Revision ID: 6d8ad5a37478
Revises: b3ef32078656
Create Date: 2024-05-15 16:26:32.974700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8ad5a37478'
down_revision = 'b3ef32078656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cats_of_the_week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('microchip', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=255), nullable=True))
        batch_op.drop_column('microchip_id')

    with op.batch_alter_table('current_round_cats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('microchip', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=255), nullable=True))
        batch_op.drop_column('microchip_id')

    with op.batch_alter_table('next_round_cats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('microchip', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=255), nullable=True))
        batch_op.drop_column('microchip_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('next_round_cats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('microchip_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('color')
        batch_op.drop_column('microchip')
        batch_op.drop_column('birth_date')

    with op.batch_alter_table('current_round_cats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('microchip_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('color')
        batch_op.drop_column('microchip')
        batch_op.drop_column('birth_date')

    with op.batch_alter_table('cats_of_the_week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('microchip_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('color')
        batch_op.drop_column('microchip')
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
