"""empty message

Revision ID: 75dae851eded
Revises: 96ad701fc2c2
Create Date: 2023-05-27 18:15:49.801220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75dae851eded'
down_revision = '96ad701fc2c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes_history',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('voter_pk', sa.Integer(), nullable=True),
    sa.Column('cat_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cat_pk'], ['cats.pk'], ),
    sa.ForeignKeyConstraint(['voter_pk'], ['voter.pk'], ),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('cat_pk'),
    sa.UniqueConstraint('voter_pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes_history')
    # ### end Alembic commands ###
