"""Add cat table

Revision ID: 842d2b410b64
Revises: 98e08d9be2f9
Create Date: 2023-04-02 21:53:55.975005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842d2b410b64'
down_revision = '98e08d9be2f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cats',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('create_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('passport_id', sa.String(length=255), nullable=False),
    sa.Column('microchip_id', sa.String(length=255), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=False),
    sa.Column('breed', sa.String(length=255), nullable=True),
    sa.Column('uploader_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_pk'], ['uploaders.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cats')
    # ### end Alembic commands ###
