"""Remove passport id

Revision ID: b3ef32078656
Revises: d051dd7acc36
Create Date: 2024-05-15 16:20:04.384971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ef32078656'
down_revision = 'd051dd7acc36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cats_of_the_week', schema=None) as batch_op:
        batch_op.drop_column('passport_id')

    with op.batch_alter_table('current_round_cats', schema=None) as batch_op:
        batch_op.drop_column('passport_id')

    with op.batch_alter_table('next_round_cats', schema=None) as batch_op:
        batch_op.drop_column('passport_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('next_round_cats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passport_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('current_round_cats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passport_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('cats_of_the_week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passport_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
