"""Retry to add images

Revision ID: b489175db508
Revises: cedbcfe192b6
Create Date: 2024-05-15 14:37:29.347490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b489175db508'
down_revision = 'cedbcfe192b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    with op.batch_alter_table('cats_of_the_week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['photo_id'])
        batch_op.create_foreign_key(None, 'images', ['photo_id'], ['pk'])

    with op.batch_alter_table('current_round_cats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['photo_id'])
        batch_op.create_foreign_key(None, 'images', ['photo_id'], ['pk'])

    with op.batch_alter_table('next_round_cats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['photo_id'])
        batch_op.create_foreign_key(None, 'images', ['photo_id'], ['pk'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('next_round_cats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('photo_id')

    with op.batch_alter_table('current_round_cats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('photo_id')

    with op.batch_alter_table('cats_of_the_week', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('photo_id')

    op.drop_table('images')
    # ### end Alembic commands ###
