"""Add images table

Revision ID: cedbcfe192b6
Revises: 0b5d6e847d5c
Create Date: 2024-05-15 14:34:50.052562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cedbcfe192b6'
down_revision = '0b5d6e847d5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cats_of_the_week', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    with op.batch_alter_table('current_round_cats', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    with op.batch_alter_table('next_round_cats', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('next_round_cats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    with op.batch_alter_table('current_round_cats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    with op.batch_alter_table('cats_of_the_week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
