"""Chage column name

Revision ID: d051dd7acc36
Revises: b489175db508
Create Date: 2024-05-15 16:15:43.198068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd051dd7acc36'
down_revision = 'b489175db508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cats_of_the_week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_pk', sa.Integer(), nullable=True))
        batch_op.drop_constraint('cats_of_the_week_photo_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['photo_pk'])
        batch_op.drop_constraint('cats_of_the_week_photo_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'images', ['photo_pk'], ['pk'])
        batch_op.drop_column('photo_id')

    with op.batch_alter_table('current_round_cats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_pk', sa.Integer(), nullable=True))
        batch_op.drop_constraint('current_round_cats_photo_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['photo_pk'])
        batch_op.drop_constraint('current_round_cats_photo_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'images', ['photo_pk'], ['pk'])
        batch_op.drop_column('photo_id')

    with op.batch_alter_table('next_round_cats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_pk', sa.Integer(), nullable=True))
        batch_op.drop_constraint('next_round_cats_photo_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['photo_pk'])
        batch_op.drop_constraint('next_round_cats_photo_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'images', ['photo_pk'], ['pk'])
        batch_op.drop_column('photo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('next_round_cats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('next_round_cats_photo_id_fkey', 'images', ['photo_id'], ['pk'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('next_round_cats_photo_id_key', ['photo_id'])
        batch_op.drop_column('photo_pk')

    with op.batch_alter_table('current_round_cats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('current_round_cats_photo_id_fkey', 'images', ['photo_id'], ['pk'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('current_round_cats_photo_id_key', ['photo_id'])
        batch_op.drop_column('photo_pk')

    with op.batch_alter_table('cats_of_the_week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cats_of_the_week_photo_id_fkey', 'images', ['photo_id'], ['pk'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('cats_of_the_week_photo_id_key', ['photo_id'])
        batch_op.drop_column('photo_pk')

    # ### end Alembic commands ###
